server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/startup
spring.datasource.username=postgres
spring.datasource.password=idkman321@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=NK25uDuA5T6NVSnnEtM3lEgT9Amlsf7QPe4japdDnEbSPMBcImZUsFGMrJXUUIP26wVkzVJSOBexZjXVFiuGrP
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

file.upload-dir=uploads/
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
