server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/DB_NAME
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=TksyNXVEdUE1VDZOVlNubkV0TTNsRWdUOUFtbHNmN1FQZTRqYXBkRG5FYlNQTUJjSW1aVXNGR01ySlhVVUlQMjZ3Vmt6VkpTT0JleFpqWFZGaXVHclA=
app.jwt.access-token-expiration=900000
app.jwt.refresh-token-expiration=604800000

app.upload.dir=uploads/
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

#Our webiste connection
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173 

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=email
spring.mail.password=password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html